dist: xenial
env:
  global:
  - secure: U5SI50amkwC2PXAi9QX1Y0duQ6S0uYscYBOURBjYJpMBq15VOwHTLZNZ0PcVikAMUUq9NblwxIXxw5dnQTPVNJkbmG2hZnTPjYU9i9ftiFnTgmNcedUDy6v0GLZYpuhFmmkWe1MTGocBFMtFmBKToAJn8FCZdmw/am3CwT6c/U5CdoSr11gm8MHIoEIjJzksbm0MXAchNa/76mdhB/z52HmbR/CtwOsE5PT8JcfkxJhC0Ayi0ZvtGtGfUsFNQ3HOemdUAw3afifs5t2BGo6uH0cbyJ5oiw7lXZKCuO1mngy3ZRRx08jXV3HPYbDDrMGug/tiI9MwLOvbVNNCmlLBv5c5zrSRyBVS10QZCuS4kxaXn5hmcG8C3MLPMMhi+058c2YoMd+ahM8GYqbvBbuPvgSUd527Bw7pdCFiFYuj9zkghtjt9kj+Tx0MjBVMtAfzWnFf5SfiASVtzbwRweqJ2Ab3p4fCO93OqcTZjsgHuXP+LVKhSuqbv5VHZHXNyifusKiws9ZqQoengjazF60GAGSWxgmeD3as5w4WJpNxWs24a7WS0p9hnveO//Ev9GcLbM6zDOAUuKFgaGgHD0etUCd1g9aT+kMA6QfaaMsz/HlVI3j0Bka8Sxt9sgwPeIod5yDgP3Bm2oFwcyMZInbKLPYE80tHI9Y+BgazdfJIQTw=
  - secure: HFDEgy3LkJBywIK4+YhGpTRPTy4aq7WYxOUFiEjS62DNK9jnhN8CnMOg+AmYZc6Spkcty0G23NK9BsTKUJuJldCxpm4ola/laHCB9XfhOYq4KGh3q2bSAOT5DLX3Q7xaJQQ4oJWBTSHyxt4IpW/3QWlWMkq89fVu8DKKtY2hzwdiMJQRyvp8OZVPgZyd4sUHLJdVrxST1DQlNjqqZIifYUf7TMv5yIB11UJp+rHfDBxzMEobpOlXQYeo0Z1mlgQD921CObCsZqac97rMhqT8wsdVyyMRCmyA5eagCvrcSmz/Ukq2XDxgKOchx083csO2HuALrYA9Z1hCxipIrIz8R3wks/gmP5fi4/tiXWXHBewMMW8wQ9gNiDZTOuut5dxJecfj1uXJsiv1XOcTjgSAC3z0Ptxl3absvIT4x35GviSgQDaz98KEqNCbEB7qNQfuWp2brllL6vas9Katf2D0HQO1AX/0JP+mfZYCWF50GT7wvvSQhlucAyp5WKaVK6CTiYKJGsMgdk+2GNe+VApxUihI8yuMgj7UYuOLzjblTKJhE83BIq2EEI7evLQ30F2WbnfIfSatNM7W61eNeXNzKrTmS9oPzEuPHriquxmF9xRiZd7lo2IZpf7c44dPiGGP3vY7AFyedFACd+O4MA2WpYY0A5qCKLFQq8VonzKcH/0=
language: python
python:
- '3.7'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
before_script:
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- coverage run manage.py test
after_script:
- coverage xml
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: carlos-moreno-spacex-api
